---

# Default directory structure for IOC deployments
install_ioc_base_directory: "/epics"
install_ioc_common_directory: "{{ install_ioc_base_directory }}/common"
install_ioc_iocs_directory: "{{ install_ioc_base_directory }}/iocs"
install_ioc_ioc_directory:
  "{{ install_ioc_iocs_directory }}/{{ install_ioc_ioc_name }}"
# Autosave directory configuration
install_ioc_as_dir_name: "as"
install_ioc_as_directory:
  "{{ install_ioc_ioc_directory }}/{{ install_ioc_as_dir_name }}"

# Specifies what post deployment step to take for each IOC.
install_ioc_post_deploy_step: "None"

# The two below are concatenated to form the full IOC executable path,
# and its associated dbd file. These can be overridden as needed.
install_ioc_template_root_path: "/usr/lib/epics"
install_ioc_executable: "softIoc"

# Use standard st.cmd file, which loads `epicsEnv.cmd`, `base.cmd`, `common.cmd`,
# executes iocInit(), and then loads `postInit.cmd`
install_ioc_standard_st_cmd: true

# If using standard startup script, specify whether `common.cmd` should be used.
# Sets up autosave passes, loads standard databases like iocStats, reccaster, etc.
install_ioc_use_common: true
install_ioc_use_ad_common: false

# Specify whether EPICS databases should be loaded as substitution files
# i.e. dbLoadTemplate, or directly as db files, i.e. dbLoadRecords.
install_ioc_load_as_substitutions: true

# Manage-iocs starting port number
install_ioc_nextport: 4000

# Dictionary mapping OS environment variable names to their values.
# Set before the IOC startup script is run.
install_ioc_os_env_exports: {}

# List of non-standard autosave req files that should be loaded.
install_ioc_req_file_list: []

# List of PV names and values that should be set after IOC startup.
install_ioc_dbpf_list: []

# List supported EL versions. By default, support EL 8 and 9.
# Support EL 10 pending https://github.com/ralphlange/procServ/issues/71
install_ioc_supported_el_versions: [8, 9]

# Specify whether or not to call `makeAutosaveFilesFromDbInfo()` at IOC startup.
install_ioc_make_autosave_files: false

# A dict mapping filenames to file contents for manual IOC files.
# Files are placed based on extension: .cmd -> iocBoot, .req -> autosave/req,
# .db/.template/.substitutions -> db
# install_ioc_manual_ioc_files: {}

# A dict for device-specific environment variables. Override this as needed
# to provide custom environment configurations for specific devices.
install_ioc_device_specific_env: {}
install_ioc_default_env:
  IOC: "{{ ioc.type }}"
  IOC_DIR: "{{ install_ioc_iocs_directory }}"
  TOP: "$(IOC_DIR)/{{ install_ioc_ioc_name }}"
  TEMPLATE_TOP: "{{ install_ioc_template_root_path }}"
  HOSTNAME: "{{ inventory_hostname.split('.')[0] }}"
  IOCNAME: "{{ install_ioc_ioc_name }}"

  # Same default EPICS locations for common modules as install_module
  ASYN: /usr/lib/epics
  AUTOSAVE: /usr/lib/epics
  BUSY: /usr/lib/epics
  CALC: /usr/lib/epics
  DEVIOCSTATS: /usr/lib/epics
  SSCAN: /usr/lib/epics
  STREAM: /usr/lib/epics
  SNCSEQ: /usr/lib/epics
  RECCASTER: /usr/lib/epics
  EPICS_BASE: /usr/lib/epics

install_ioc_required_system_packages:
  - procServ

# For python-based IOCs, we use `pixi` to init the environments. By default,
# assume it's in the PATH on the target machine. This can be overridden.
install_ioc_pixi_executable_path: pixi

# adaravis defaults
device_roles_adaravis_genicam_xml_converters_url:
  https://github.com/jwlodek/genicam-xml-converters
device_roles_adaravis_genicam_xml_converters_version: "224b03b"

# axis_caproto defaults
device_roles_axis_caproto_python_version: ">=3.10,<3.13"
device_roles_axis_caproto_srx_caproto_iocs_git_revision: "v0.1.0"

# germcaproto defaults
device_roles_germcaproto_python_version: ">=3.10,<3.13"

# hiden_stream defaults
device_roles_hiden_stream_hiden_git_revision: "v0.1.0"
device_roles_hiden_stream_python_version: ">=3.10,<3.13"

# motorsim defaults
device_roles_motorsim_default_res: 0.01
device_roles_motorsim_soft_limit_offset: 10

# pandabox defaults
device_roles_pandabox_pip_dependencies:
  - "pandablocks-ioc==0.11.5"

# zebra_saver_caproto defaults
device_roles_zebra_saver_caproto_python_version: ">=3.10,<3.13"
device_roles_zebra_saver_caproto_srx_caproto_iocs_git_revision: "v0.1.0"
