---
# Set to true to skip module compilation (for roles requiring proprietary SDKs)
skip_compilation: false

verification:
  files_must_exist:
    # Standard IOC boot files (created by deploy_ioc)
    - iocBoot/st.cmd
    - iocBoot/epicsEnv.cmd
    - iocBoot/postInit.cmd
    # Role-specific files
    - iocBoot/base.cmd
    - db/test.db
    - db/test.substitutions
    - db/test-gen-fixed-params.substitutions
    - db/test-gen-variable-params.substitutions

  file_must_contain:
    iocBoot/st.cmd:
      - "iocInit"
    iocBoot/base.cmd:
      - "dbLoadDatabase"
      - "baseSoftIOC_registerRecordDeviceDriver(pdbbase)"
    iocBoot/common.cmd:
      - "dbLoadTemplate(\"$(TOP)/db/test-gen-fixed-params.substitutions\")"
      - "dbLoadTemplate(\"$(TOP)/db/test-gen-variable-params.substitutions\", \"P=$(SYS),DEV=$(DEV)\")"
      - "dbLoadTemplate(\"$(TOP)/db/test.substitutions\")"
    db/test.db:
      - "record(ao, \"$(P)$(R)pv\")"
    db/test.substitutions:
      - "file \"$(TOP)/db/test.db\""
    db/test-gen-fixed-params.substitutions:
      - "file \"$(TOP)/db/test.db\""
      - "{\"TEST\", \"{PRM:FIXED}\"}"
    db/test-gen-variable-params.substitutions:
      - "file \"$(TOP)/db/test.db\""
      - "{R}"
      - "{\"$(DEV)\"}"

  file_must_not_contain:
    iocBoot/st.cmd:
      - "{{"  # No unrendered jinja
      - "}}"
    iocBoot/base.cmd:
      - "{{"
      - "}}"
      - 'asynSetOption'
    iocBoot/common.cmd:
      - "{{"
      - "}}"
    iocBoot/epicsEnv.cmd:
      - "{{"
      - "}}"
    db/test-gen-fixed-params.substitutions:
      - "{{"
      - "}}"
    db/test-gen-variable-params.substitutions:
      - "{{"
      - "}}"

  permissions:
    iocBoot/st.cmd: "0775"
