---

type: enum("caparoc")
environment:
  SYS: str()
  DEV: str()
  HOST: str()
  CB_ASYNPORT: str()
  PREFIX: str()
  ENGINEER: str()

operations: list(include('operation'), min=1)

---

operation:
  PORT_NAME: str()
  MODBUS_FUNC: int()
  START_ADDR: int()
  MODBUS_LEN: int()
  DATA_TYPE: enum("UINT16", "INT16", "UINT32", "INT32", "FLOAT32", "FLOAT64", "STRING_HIGH_LOW")
