---

# Tasks for wienercrate role

- name: Create mibs directory
  ansible.builtin.file:
    path: "{{ install_ioc_ioc_directory }}/mibs"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    state: directory
    mode: "0775"

- name: Copy MIB file
  ansible.builtin.copy:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/files/WIENER-CRATE-MIB.txt"
    dest: "{{ install_ioc_ioc_directory }}/mibs"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Copy databases file (wienerCrate.db)
  ansible.builtin.copy:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/files/wienerCrate.db"
    dest: "{{ install_ioc_ioc_directory }}/db"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Copy databases file (supplies.db)
  ansible.builtin.copy:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/files/supplies.db"
    dest: "{{ install_ioc_ioc_directory }}/db"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Install base startup script
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/base.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
