---

install_ioc_use_common: true
install_ioc_use_ad_common: false
install_ioc_required_module: linkam3_1093365
install_ioc_executable: linkamT96App
install_ioc_template_root_path:
  "{{ install_ioc_required_module_path }}/iocs/linkamIOC"
install_ioc_device_specific_env:
  LINKAM3_LICENSE_PATH: /etc/linkam/Linkam.lsk
