---

- name: Install base.cmd
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/base.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/iocBoot/base.cmd"
    mode: "0664"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"

- name: Create protocol directory
  ansible.builtin.file:
    path: "{{ install_ioc_ioc_directory }}/protocol"
    state: directory
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0775"

- name: Copy databases file for Stanford DG645
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ install_ioc_ioc_directory }}/db"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
  with_fileglob: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/files/*.template"

- name: Copy protocol file for Stanford DG645
  ansible.builtin.copy:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/files/dg645.proto"
    dest: "{{ install_ioc_ioc_directory }}/protocol/dg645.proto"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
