---
# Tasks for adpco role

- name: Install base.cmd
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/base.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/iocBoot/base.cmd"
    mode: "0664"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"


- name: Install auto_settings.req
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/auto_settings.req.j2"
    dest: "{{ install_ioc_as_directory }}/req/auto_settings.req"
    mode: "0664"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
