---
- name: Install acmi2 base startup commands
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/base.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Create settings directory
  ansible.builtin.file:
    path: "{{ install_ioc_ioc_directory }}/settings"
    state: directory
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "02775"

- name: Copy settings file from source repo
  ansible.builtin.copy:
    src: "{{ install_ioc_required_module_path }}/settings/settings.txt"
    dest: "{{ install_ioc_ioc_directory }}/settings/settings.txt"
    remote_src: true
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Create COW directory
  ansible.builtin.file:
    path: "{{ install_ioc_ioc_directory }}/COW"
    state: directory
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "02775"

- name: Create Correction directory
  ansible.builtin.file:
    path: "{{ install_ioc_ioc_directory }}/Correction"
    state: directory
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "02775"

- name: Copy ADC correction table files from source repo
  ansible.builtin.copy:
    src: "{{ install_ioc_required_module_path }}/Correction/"
    dest: "{{ install_ioc_ioc_directory }}/Correction/"
    remote_src: true
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
