---

install_ioc_template_root_path: "{{ install_ioc_required_module_path }}"
install_ioc_required_module: motorpigcs2_a0bdeae
install_ioc_make_autosave_files: true
install_ioc_executable: pigcs2
install_ioc_device_specific_env:
  MOTOR_PIGCS2: "/epics/modules/motorPIGCS2"
