---

- name: Copy base.cmd
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/base.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Copy autosave req file
  ansible.builtin.copy:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/files/auto_settings.req"
    dest: "{{ install_ioc_as_directory }}/req/auto_settings.req"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
