---
install_ioc_standard_st_cmd: true
install_ioc_executable: "quadEMTestApp"
install_ioc_as_dir_name: autosave
install_ioc_template_root_path: "{{ install_ioc_required_module_path }}"
install_ioc_required_module: quadem_f5ab1e9
install_ioc_use_common: true
install_ioc_req_file_list:
  - name: auto_settings.req
    macros: "P=$(PREFIX)"
install_ioc_device_specific_env:
  TEMPLATE: "TetrAMM"
  PORT: "TetrAMM"
  QSIZE: 20
  RING_SIZE: 10000
  TSPOINTS: 10000
  MAX_THREADS: 8
  EPICS_CA_MAX_ARRAY_BYTES: 5000000
