---

- name: Install EPICS environment file
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/epicsEnv.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/epicsEnv.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Install base startup script
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/st.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/st.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0775"
