---
# Tasks for omega_rtc role

- name: Install base.cmd
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/base.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/iocBoot/base.cmd"
    mode: "0664"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"

- name: Install custom postInit.cmd
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/postInit.cmd.j2"
    dest: "{{ install_ioc_ioc_directory }}/iocBoot/postInit.cmd"
    mode: "0664"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"

- name: Install custom alarm.db
  ansible.builtin.template:
    src: "{{ role_path }}/tasks/device_types/{{ ioc.type }}/templates/alarm.db.j2"
    dest: "{{ install_ioc_ioc_directory }}/db/alarm.db"
    mode: "0664"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
