---

type: enum("omega_rtc")
devices: list(include('device'))
environment:
  ENGINEER: str()
  PREFIX: str()
  SYS: str()

---
device:
  SYS: str()
  DEV: str()
  PORT: str()
  HOST: str()
  CHAN: str(required=False, default="01")
  COMM: enum("RS-232", "RS-485", required=False)
