---
mc03:
  type: powerpmac
  environment:
    SYS: "XF:31ID1-OP:1"
    CONTROLLER: "MC:03"
    DEV: "{$(CONTROLLER)}"
    CT_SYS: "XF:31ID1-CT"
    NUM_AXES: 8 # Controller has 8 axes; only X is configured in this example
    ENGINEER: "J. Wlodek"
    MOVING_POLL_PERIOD: 100
    IDLE_POLL_PERIOD: 1000
    CONTROLLER_IP: "xf31id1-lab3-mc3.nsls2.bnl.local"

  axes:
    - name: "X"
      num: 1
      component: CMT:1
      desc: "X translation"
      mres: 0.045
      egu: "mm"
      disable_limits: false
