---

- name: Set deployment facts
  ansible.builtin.include_tasks: set-facts.yml

- name: Initialize install_ioc_loop_index only if not defined
  ansible.builtin.set_fact:
    install_ioc_loop_index: 0
  when: install_ioc_loop_index is not defined

- name: Stop existing IOC instance if running
  when: >
    install_ioc_post_deploy_step == "Restart" or
    "Start" in install_ioc_post_deploy_step
  block:
    - name: Check if IOC service exists
      ansible.builtin.stat:
        path: /etc/systemd/system/softioc-{{ install_ioc_ioc_name }}.service
      register: install_ioc_service_file

    - name: Ensure IOC service is stopped
      ansible.builtin.include_role:
        name: manage_iocs
      vars:
        manage_iocs_command: "stop"
        manage_iocs_subcommand: "{{ install_ioc_ioc_name }}"
      when: install_ioc_service_file.stat.exists

- name: Create IOC directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ install_ioc_ioc_directory }}"
    state: directory
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "02775"


- name: Perform base setup when using standard startup script format
  when: install_ioc_standard_st_cmd
  block:
    - name: Create standard IOC dirs
      ansible.builtin.file:
        path: "{{ install_ioc_ioc_directory }}/{{ item }}"
        owner: "{{ host_config.softioc_user }}"
        group: "{{ host_config.softioc_group }}"
        state: directory
        mode: "02775"
      with_items:
        - "db"
        - "iocBoot"
        - "{{ install_ioc_as_dir_name }}"
        - "{{ install_ioc_as_dir_name }}/req"
        - "{{ install_ioc_as_dir_name }}/save"

    - name: Generate substitutions based on IOC configuration
      ansible.builtin.include_tasks: generate-substitutions-file.yml
      loop: "{{ ioc.substitutions | dict2items }}"
      when: ioc.substitutions is defined and install_ioc_load_as_substitutions

    - name: Generate common cmd file
      ansible.builtin.template:
        src: templates/common.cmd.j2
        dest: "{{ install_ioc_ioc_directory }}/iocBoot/common.cmd"
        owner: "{{ host_config.softioc_user }}"
        group: "{{ host_config.softioc_group }}"
        mode: "0664"
      when: install_ioc_use_common

    - name: Install remaining standard iocBoot templates
      ansible.builtin.template:
        src: "templates/{{ item }}.j2"
        dest: "{{ install_ioc_ioc_directory }}/iocBoot/{{ item }}"
        owner: "{{ host_config.softioc_user }}"
        group: "{{ host_config.softioc_group }}"
        mode: "0664"
      with_items:
        - epicsEnv.cmd
        - postInit.cmd
        - st.cmd

    - name: Ensure nested startup script is executable
      ansible.builtin.file:
        path: "{{ install_ioc_ioc_directory }}/iocBoot/st.cmd"
        mode: "0775"

    - name: Install top level IOC startup script
      ansible.builtin.template:
        src: templates/st_top.cmd.j2
        dest: "{{ install_ioc_ioc_directory }}/st.cmd"
        owner: "{{ host_config.softioc_user }}"
        group: "{{ host_config.softioc_group }}"
        mode: "0775"

    - name: Copy manual IOC files to appropriate directories
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: >-
          {{ install_ioc_ioc_directory }}/{{
            'iocBoot' if item.key.endswith('.cmd')
            else install_ioc_as_dir_name ~ '/req' if item.key.endswith('.req')
            else 'db'
          }}/{{ item.key }}
        owner: "{{ host_config.softioc_user }}"
        group: "{{ host_config.softioc_group }}"
        mode: "0664"
      loop: "{{ install_ioc_manual_ioc_files | dict2items }}"
      when:
        - install_ioc_manual_ioc_files is defined
        - install_ioc_manual_ioc_files | length > 0
        - item.key | regex_search('\.(cmd|req|db|template|substitutions)$')

- name: Deploy IOC template
  ansible.builtin.include_tasks:
    file: "device_types/{{ ioc.type }}/main.yml"

- name: Writeout IOC configuration used to yml
  ansible.builtin.copy:
    content: "{{ {install_ioc_ioc_name: ioc} | to_nice_yaml(sort_keys=False) }}"
    dest: "{{ install_ioc_ioc_directory }}/{{ install_ioc_ioc_name }}.yml"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Generate IOC README file
  ansible.builtin.template:
    src: templates/README.md.j2
    dest: "{{ install_ioc_ioc_directory }}/README.md"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Generate manage-iocs config file
  ansible.builtin.include_tasks: update-config.yml

- name: Ensure ownership of all files and directories is correct
  ansible.builtin.command:
    cmd: "chown -R {{ host_config.softioc_user }}:{{ host_config.softioc_group }} {{ install_ioc_ioc_directory }}"
  changed_when: true

- name: Query IOC directory ACLs
  ansible.posix.acl:
    path: "{{ install_ioc_ioc_directory }}"
    state: query
  register: install_ioc_ioc_directory_acl_query
  changed_when: false

- name: Get IOC directory ACL users and groups
  ansible.builtin.set_fact:
    install_ioc_group_acls: >-
      {{
        (
          install_ioc_group_acls | default([])
        )
        + (
          install_ioc_ioc_directory_acl_query.acl
          | select('match', '^(default:)?group:[^:]+:')
          | reject('match', '^(default:)?group::')
          | map('regex_replace', '^(?:default:)?group:([^:]+):.*$', '\1')
          | list
        )
        | unique
      }}
    install_ioc_user_acls: >-
      {{
        (
          install_ioc_user_acls | default([])
        )
        + (
          install_ioc_ioc_directory_acl_query.acl
          | select('match', '^(default:)?user:[^:]+:')
          | reject('match', '^(default:)?user::')
          | map('regex_replace', '^(?:default:)?user:([^:]+):.*$', '\1')
          | list
        )
        | unique
      }}
  changed_when: false

- name: Make contents of EPICS writable by groups via ACLs
  ansible.builtin.command: >-
    setfacl -nR{{ item.1 }}m g:{{ item.0 }}:rwX {{ install_ioc_ioc_directory }}
  changed_when: true
  loop: >-
    {{ install_ioc_group_acls | product(['', 'd']) | list }}
  loop_control:
    label: "{{ item.0 }}{{ ' default' if 'd' in item.1 else '' }}"

- name: Make contents of EPICS writable by users via ACLs
  ansible.builtin.command: >-
    setfacl -nR{{ item.1 }}m u:{{ item.0 }}:rwX {{ install_ioc_ioc_directory }}
  changed_when: true
  loop: >-
    {{ install_ioc_user_acls |
       product(['', 'd']) | list }}
  loop_control:
    label: "{{ item.0 }}{{ ' default' if 'd' in item.1 else '' }}"

- name: Perform post-deployment IOC setup tasks
  when: install_ioc_post_deploy_step != "None"
  block:
    - name: Auto install IOC
      ansible.builtin.include_role:
        name: nsls2.ioc_deploy.manage_iocs
      vars:
        manage_iocs_command: "install"
        manage_iocs_subcommand: "{{ install_ioc_ioc_name }}"
      when:
        - install_ioc_post_deploy_step == "Install" or
          install_ioc_post_deploy_step == "Install and Enable" or
          install_ioc_post_deploy_step == "Install and Start" or
          install_ioc_post_deploy_step == "Install and Enable and Start"

    - name: Auto enable IOC
      ansible.builtin.include_role:
        name: manage_iocs
      vars:
        manage_iocs_command: "enable"
        manage_iocs_subcommand: "{{ install_ioc_ioc_name }}"
      when:
        - install_ioc_post_deploy_step == "Install and Enable" or
          install_ioc_post_deploy_step == "Install and Enable and Start"

    - name: Auto restart IOC
      ansible.builtin.include_role:
        name: manage_iocs
      vars:
        manage_iocs_command: "restart"
        manage_iocs_subcommand: "{{ install_ioc_ioc_name }}"
      when:
        - install_ioc_post_deploy_step == "Restart" or
          install_ioc_post_deploy_step == "Install and Start" or
          install_ioc_post_deploy_step == "Install and Enable and Start"
