---

install_ioc_use_common: true
install_ioc_use_ad_common: true
install_ioc_required_module: 'adtimepix3_2faf970'
install_ioc_executable: tpx3App

install_ioc_template_root_path:
  "{{ install_ioc_required_module_path }}/iocs/tpx3IOC"
install_ioc_req_file_list:
  - name: auto_settings.req
    macros: "P=$(PREFIX)"
install_ioc_device_specific_env:
  PORT: "TPX"
  QSIZE: 20
  NCHANS: 2048
  CBUFFS: 500
  MAX_THREADS: 8
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db"
